version: '3.3'
services:
  email:
    container_name: anonimes-email
    restart: always
    build: ./EmailMicroService
    ports:
      - "5001:4001"
  nas:
    container_name: anonimes-nas
    restart: always
    build: ./NasMicroService
    volumes:
      - ../AnonymousFilesNAS:/usr/src/api/uploads
    ports:
      - "5002:4002"
